# awk script for soversions.i -> gnu/lib-names.h; see Makeconfig.

$1 != "DEFAULT" { multi = 1 }

#
{
  lib = $2;
  version = $3;
  if ($3 !~ /^[0-9]/) {
    soname = $3;
    extra = $3;
    sub(/\.so.*$/, "", extra);
  }
  else {
    soname = lib ".so." $3;
    extra = "";
  }
  soname = "\"" soname "\"";
  lib = toupper(lib);
  extra = toupper(extra);
  gsub(/-/, "_", lib);
  gsub(/-/, "_", extra);
  if (extra) {
    if (extra == "LD_LINUX_X32") {
      x32_macros[$1 FS lib "_SO"] = soname;
      x32_macros[$1 FS extra "_SO"] = soname;
      x86_64_macros[$1 FS lib "_SO"] = "\"ld-linux-x86-64.so.2\"";
      x86_64_macros[$1 FS "LD_LINUX_X86_64_SO"] = "\"ld-linux-x86-64.so.2\"";
    }
    else if (extra == "LD_LINUX_X86_64") {
      x86_64_macros[$1 FS lib "_SO"] = soname;
      x86_64_macros[$1 FS extra "_SO"] = soname;
      x32_macros[$1 FS lib "_SO"] = "\"ld-linux-x32.so.2\"";
      x32_macros[$1 FS "LD_LINUX_X32_SO"] = "\"ld-linux-x32.so.2\"";
    }
    else {
      macros[$1 FS lib "_SO"] = soname;
      macros[$1 FS extra "_SO"] = soname;
    }
  }
  else {
    macros[$1 FS lib "_SO"] = soname;
  }
}

END {
  print "/* This file is automatically generated.";
  print "   It defines macros to allow user program to find the shared";
  print "   library files which come as part of GNU libc.  */";
  print "#ifndef __GNU_LIB_NAMES_H";
  print "#define __GNU_LIB_NAMES_H	1";
  print "";

  pfx = multi ? "# define " : "#define ";
  for (elt in macros) {
    split(elt, x);
    line = sprintf("%-40s%s", pfx x[2], macros[elt]);
    if (x[1] in lines)
      lines[x[1]] = lines[x[1]] "\n" line;
    else
      lines[x[1]] = line;
  }

  if (multi) {
    # Print these in a fixed order so the result is identical
    # on both sides of the coin.
    pfx = "#  define ";
    for (elt in x32_macros) {
      split(elt, x);
      line = sprintf("%-40s%s", pfx x[2], x32_macros[elt]);
      if (x[1] in x32_lines)
	x32_lines[x[1]] = x32_lines[x[1]] "\n" line;
      else
	x32_lines[x[1]] = line;
    }
    for (elt in x86_64_macros) {
      split(elt, x);
      line = sprintf("%-40s%s", pfx x[2], x86_64_macros[elt]);
      if (x[1] in x86_64_lines)
	x86_64_lines[x[1]] = x86_64_lines[x[1]] "\n" line;
      else
	x86_64_lines[x[1]] = line;
    }
    if (!("WORDSIZE32" in lines))
      lines["WORDSIZE32"] = lines["DEFAULT"];
    if (!("WORDSIZE64" in lines))
      lines["WORDSIZE64"] = lines["DEFAULT"];
    if (!("WORDSIZE32" in x32_lines))
      x32_lines["WORDSIZE32"] = x32_lines["DEFAULT"];
    if (!("WORDSIZE64" in x32_lines))
      x32_lines["WORDSIZE64"] = x32_lines["DEFAULT"];
    if (!("WORDSIZE32" in x86_64_lines))
      x86_64_lines["WORDSIZE32"] = x86_64_lines["DEFAULT"];
    if (!("WORDSIZE64" in x86_64_lines))
      x86_64_lines["WORDSIZE64"] = x86_64_lines["DEFAULT"];
    print "#include <bits/wordsize.h>\n";
    print "#ifndef __x86_64__";
    cmd = "LC_ALL=C sort"; print lines["WORDSIZE32"] | cmd; close(cmd);
    print "#else"
    print "# if __WORDSIZE == 32"
    cmd = "LC_ALL=C sort"; print x32_lines["WORDSIZE64"] | cmd; close(cmd);
    print "# else"
    cmd = "LC_ALL=C sort"; print x86_64_lines["WORDSIZE64"] | cmd; close(cmd);
    print "# endif"
    cmd = "LC_ALL=C sort"; print lines["WORDSIZE64"] | cmd; close(cmd);
    print "#endif";
  }
  else {
    cmd = "LC_ALL=C sort"; print lines["DEFAULT"] | cmd; close(cmd);
  }

  print "";
  print "#endif	/* gnu/lib-names.h */"
}
